// <auto-generated />
namespace MuseumProject.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddCounter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCounter));
        
        string IMigrationMetadata.Id
        {
            get { return "201501212115107_AddCounter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
