// <auto-generated />
namespace MuseumProject.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addBaseInformationTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addBaseInformationTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201502151132051_addBaseInformationTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
